services:
  magicmirror:
    image: karsten13/magicmirror:latest
    restart: unless-stopped
    ports:
    - 8080:8080
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
      ## @armV8 architecture the docker image runs in electron mode by default
      ## to prevent this, we need to override the scenario
      MM_SCENARIO: server
    volumes:
    - ./data/magicmirror/config:/opt/magic_mirror/config
    - ./data/magicmirror/css:/opt/magic_mirror/css
    networks:
    - mmnetwork
  puppeteer:
    build:
      dockerfile: waveshare.Dockerfile
    depends_on:
      magicmirror:
        condition: service_healthy
    volumes:
    - ./data/screenshot:/app/static
    restart: unless-stopped
    environment:
      ENV GPIOZERO_PIN_FACTORY: lgpio
    devices:
    - /dev/gpiochip0:/dev/gpiochip0
    - /dev/gpiochip1:/dev/gpiochip1
    - /dev/gpiochip2:/dev/gpiochip2
    - /dev/gpiochip4:/dev/gpiochip4
    - /dev/spidev0.0:/dev/spidev0.0
    - /dev/spidev0.1:/dev/spidev0.1
    cap_add:
    - SYS_ADMIN
    networks:
    - mmnetwork
networks:
  mmnetwork:

