services:
  magicmirror:
    image: karsten13/magicmirror:latest
    restart: unless-stopped
    ports:
    - 8044:8080
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
    volumes:
    - ./data/magicmirror/config:/opt/magic_mirror/config
    - ./data/magicmirror/css:/opt/magic_mirror/css
    networks:
    - mmnetwork
  puppeteer:
    build:
      dockerfile: waveshare.Dockerfile
    depends_on:
      magicmirror:
        condition: service_healthy
    # volumes:
    # - ./data/app:/app/
    restart: unless-stopped
    devices:
    - /dev/gpiochip4:/dev/gpiochip4
    cap_add:
    - SYS_ADMIN
    networks:
    - mmnetwork
networks:
  mmnetwork:

